#!/bin/bash
#PBS -N GLMNET
#PBS -l select=1:ncpus=128:mem=256gb
#PBS -l walltime=16:00:00
#PBS -o output.txt
#PBS -e error.txt

# Move to the directory from which the job was submitted
cd "$PBS_O_WORKDIR"

# Load required modules
module purge
module add tools/prod

# Activate Conda environment
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate Renv

# Run the R script (no array index needed)
Rscript "Predictive Regression.R"


