#!/bin/bash
#PBS -N NetworkCluster
#PBS -l select=1:ncpus=64:mem=100gb
#PBS -l walltime=16:00:00
#PBS -o output.txt
#PBS -e error.txt

# Change to the directory from which the job was submitted
cd "$PBS_O_WORKDIR"

# Load any required modules
module purge
module add tools/prod

# Initialize Conda (Imperial's recommended method)
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate networkanalysis

# Run your Python script
python cluster_based.py
