#!/bin/bash
#PBS -N NetworkM2
#PBS -l select=1:ncpus=32:mem=64gb:ngpus=1
#PBS -l walltime=32:00:00
#PBS -o output5.txt
#PBS -e error5.txt


# Change to the directory from which the job was submitted
cd "$PBS_O_WORKDIR"

# Load any required modules
module purge
module add tools/prod

# Initialize Conda (Imperial's recommended method)
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate networkanalysis

# Run your Python script
python pos_model_2.py
